/*
 * kabuステーションAPI
 * # 定義情報   REST APIのコード一覧、エンドポイントは下記リンク参照     - [REST APIコード一覧](../ptal/error.html)
 *
 * OpenAPI spec version: 1.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * RegulationsResponseRegulationsInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-04-09T08:07:59.802Z[GMT]")
public class RegulationsResponseRegulationsInfo {
  @SerializedName("Exchange")
  private Integer exchange = null;

  @SerializedName("Product")
  private Integer product = null;

  @SerializedName("Side")
  private String side = null;

  @SerializedName("Reason")
  private String reason = null;

  @SerializedName("LimitStartDay")
  private String limitStartDay = null;

  @SerializedName("LimitEndDay")
  private String limitEndDay = null;

  @SerializedName("Level")
  private Integer level = null;

  public RegulationsResponseRegulationsInfo exchange(Integer exchange) {
    this.exchange = exchange;
    return this;
  }

   /**
   * 規制市場 &lt;table&gt;   &lt;thead&gt;     &lt;tr&gt;       &lt;th&gt;定義値&lt;/th&gt;       &lt;th&gt;内容&lt;/th&gt;     &lt;/tr&gt;   &lt;/thead&gt;   &lt;tbody&gt;     &lt;tr&gt;       &lt;td&gt;0&lt;/td&gt;       &lt;td&gt;全対象&lt;/td&gt;     &lt;/tr&gt;     &lt;tr&gt;       &lt;td&gt;1&lt;/td&gt;       &lt;td&gt;東証&lt;/td&gt;     &lt;/tr&gt;     &lt;tr&gt;       &lt;td&gt;3&lt;/td&gt;       &lt;td&gt;名証&lt;/td&gt;     &lt;/tr&gt;     &lt;tr&gt;       &lt;td&gt;5&lt;/td&gt;       &lt;td&gt;福証&lt;/td&gt;     &lt;/tr&gt;     &lt;tr&gt;       &lt;td&gt;6&lt;/td&gt;       &lt;td&gt;札証&lt;/td&gt;     &lt;/tr&gt;     &lt;tr&gt;       &lt;td&gt;9&lt;/td&gt;       &lt;td&gt;SOR&lt;/td&gt;     &lt;/tr&gt;     &lt;tr&gt;       &lt;td&gt;10&lt;/td&gt;       &lt;td&gt;CXJ&lt;/td&gt;     &lt;/tr&gt;     &lt;tr&gt;       &lt;td&gt;21&lt;/td&gt;       &lt;td&gt;JNX&lt;/td&gt;     &lt;/tr&gt;   &lt;/tbody&gt; &lt;/table&gt;
   * @return exchange
  **/
  @Schema(description = "規制市場 <table>   <thead>     <tr>       <th>定義値</th>       <th>内容</th>     </tr>   </thead>   <tbody>     <tr>       <td>0</td>       <td>全対象</td>     </tr>     <tr>       <td>1</td>       <td>東証</td>     </tr>     <tr>       <td>3</td>       <td>名証</td>     </tr>     <tr>       <td>5</td>       <td>福証</td>     </tr>     <tr>       <td>6</td>       <td>札証</td>     </tr>     <tr>       <td>9</td>       <td>SOR</td>     </tr>     <tr>       <td>10</td>       <td>CXJ</td>     </tr>     <tr>       <td>21</td>       <td>JNX</td>     </tr>   </tbody> </table>")
  public Integer getExchange() {
    return exchange;
  }

  public void setExchange(Integer exchange) {
    this.exchange = exchange;
  }

  public RegulationsResponseRegulationsInfo product(Integer product) {
    this.product = product;
    return this;
  }

   /**
   * 規制取引区分&lt;br&gt; ※空売り規制の場合、「4：新規」 &lt;table&gt;   &lt;thead&gt;     &lt;tr&gt;       &lt;th&gt;定義値&lt;/th&gt;       &lt;th&gt;内容&lt;/th&gt;     &lt;/tr&gt;   &lt;/thead&gt;   &lt;tbody&gt;     &lt;tr&gt;       &lt;td&gt;0&lt;/td&gt;       &lt;td&gt;全対象&lt;/td&gt;     &lt;/tr&gt;     &lt;tr&gt;       &lt;td&gt;1&lt;/td&gt;       &lt;td&gt;現物&lt;/td&gt;     &lt;/tr&gt;     &lt;tr&gt;       &lt;td&gt;2&lt;/td&gt;       &lt;td&gt;信用新規（制度）&lt;/td&gt;     &lt;/tr&gt;     &lt;tr&gt;       &lt;td&gt;3&lt;/td&gt;       &lt;td&gt;信用新規（一般）&lt;/td&gt;     &lt;/tr&gt;     &lt;tr&gt;       &lt;td&gt;4&lt;/td&gt;       &lt;td&gt;新規&lt;/td&gt;     &lt;/tr&gt;     &lt;tr&gt;       &lt;td&gt;5&lt;/td&gt;       &lt;td&gt;信用返済（制度）&lt;/td&gt;     &lt;/tr&gt;     &lt;tr&gt;       &lt;td&gt;6&lt;/td&gt;       &lt;td&gt;信用返済（一般）&lt;/td&gt;     &lt;/tr&gt;     &lt;tr&gt;       &lt;td&gt;7&lt;/td&gt;       &lt;td&gt;返済&lt;/td&gt;     &lt;/tr&gt;     &lt;tr&gt;       &lt;td&gt;8&lt;/td&gt;       &lt;td&gt;品受&lt;/td&gt;     &lt;/tr&gt;     &lt;tr&gt;       &lt;td&gt;9&lt;/td&gt;       &lt;td&gt;品渡&lt;/td&gt;     &lt;/tr&gt;   &lt;/tbody&gt; &lt;/table&gt;
   * @return product
  **/
  @Schema(description = "規制取引区分<br> ※空売り規制の場合、「4：新規」 <table>   <thead>     <tr>       <th>定義値</th>       <th>内容</th>     </tr>   </thead>   <tbody>     <tr>       <td>0</td>       <td>全対象</td>     </tr>     <tr>       <td>1</td>       <td>現物</td>     </tr>     <tr>       <td>2</td>       <td>信用新規（制度）</td>     </tr>     <tr>       <td>3</td>       <td>信用新規（一般）</td>     </tr>     <tr>       <td>4</td>       <td>新規</td>     </tr>     <tr>       <td>5</td>       <td>信用返済（制度）</td>     </tr>     <tr>       <td>6</td>       <td>信用返済（一般）</td>     </tr>     <tr>       <td>7</td>       <td>返済</td>     </tr>     <tr>       <td>8</td>       <td>品受</td>     </tr>     <tr>       <td>9</td>       <td>品渡</td>     </tr>   </tbody> </table>")
  public Integer getProduct() {
    return product;
  }

  public void setProduct(Integer product) {
    this.product = product;
  }

  public RegulationsResponseRegulationsInfo side(String side) {
    this.side = side;
    return this;
  }

   /**
   * 規制売買&lt;br&gt; ※空売り規制の場合、「1：売」 &lt;table&gt;   &lt;thead&gt;     &lt;tr&gt;       &lt;th&gt;定義値&lt;/th&gt;       &lt;th&gt;内容&lt;/th&gt;     &lt;/tr&gt;   &lt;/thead&gt;   &lt;tbody&gt;     &lt;tr&gt;       &lt;td&gt;0&lt;/td&gt;       &lt;td&gt;全対象&lt;/td&gt;     &lt;/tr&gt;     &lt;tr&gt;       &lt;td&gt;1&lt;/td&gt;       &lt;td&gt;売&lt;/td&gt;     &lt;/tr&gt;     &lt;tr&gt;       &lt;td&gt;2&lt;/td&gt;       &lt;td&gt;買&lt;/td&gt;     &lt;/tr&gt;   &lt;/tbody&gt; &lt;/table&gt;
   * @return side
  **/
  @Schema(description = "規制売買<br> ※空売り規制の場合、「1：売」 <table>   <thead>     <tr>       <th>定義値</th>       <th>内容</th>     </tr>   </thead>   <tbody>     <tr>       <td>0</td>       <td>全対象</td>     </tr>     <tr>       <td>1</td>       <td>売</td>     </tr>     <tr>       <td>2</td>       <td>買</td>     </tr>   </tbody> </table>")
  public String getSide() {
    return side;
  }

  public void setSide(String side) {
    this.side = side;
  }

  public RegulationsResponseRegulationsInfo reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * 理由&lt;br&gt;※空売り規制の場合、「空売り規制」
   * @return reason
  **/
  @Schema(description = "理由<br>※空売り規制の場合、「空売り規制」")
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public RegulationsResponseRegulationsInfo limitStartDay(String limitStartDay) {
    this.limitStartDay = limitStartDay;
    return this;
  }

   /**
   * 制限開始日&lt;br&gt;yyyy/MM/dd HH:mm形式  &lt;br&gt;※空売り規制の場合、null
   * @return limitStartDay
  **/
  @Schema(description = "制限開始日<br>yyyy/MM/dd HH:mm形式  <br>※空売り規制の場合、null")
  public String getLimitStartDay() {
    return limitStartDay;
  }

  public void setLimitStartDay(String limitStartDay) {
    this.limitStartDay = limitStartDay;
  }

  public RegulationsResponseRegulationsInfo limitEndDay(String limitEndDay) {
    this.limitEndDay = limitEndDay;
    return this;
  }

   /**
   * 制限終了日&lt;br&gt;yyyy/MM/dd HH:mm形式  &lt;br&gt;※空売り規制の場合、null
   * @return limitEndDay
  **/
  @Schema(description = "制限終了日<br>yyyy/MM/dd HH:mm形式  <br>※空売り規制の場合、null")
  public String getLimitEndDay() {
    return limitEndDay;
  }

  public void setLimitEndDay(String limitEndDay) {
    this.limitEndDay = limitEndDay;
  }

  public RegulationsResponseRegulationsInfo level(Integer level) {
    this.level = level;
    return this;
  }

   /**
   * コンプライアンスレベル&lt;br&gt; ※空売り規制の場合、null &lt;table&gt;   &lt;thead&gt;     &lt;tr&gt;       &lt;th&gt;定義値&lt;/th&gt;       &lt;th&gt;内容&lt;/th&gt;     &lt;/tr&gt;   &lt;/thead&gt;   &lt;tbody&gt;     &lt;tr&gt;       &lt;td&gt;０&lt;/td&gt;       &lt;td&gt;規制無し&lt;/td&gt;     &lt;/tr&gt;     &lt;tr&gt;       &lt;td&gt;１&lt;/td&gt;       &lt;td&gt;ワーニング&lt;/td&gt;     &lt;/tr&gt;     &lt;tr&gt;       &lt;td&gt;２&lt;/td&gt;       &lt;td&gt;エラー&lt;/td&gt;     &lt;/tr&gt;   &lt;/tbody&gt; &lt;/table&gt;
   * @return level
  **/
  @Schema(description = "コンプライアンスレベル<br> ※空売り規制の場合、null <table>   <thead>     <tr>       <th>定義値</th>       <th>内容</th>     </tr>   </thead>   <tbody>     <tr>       <td>０</td>       <td>規制無し</td>     </tr>     <tr>       <td>１</td>       <td>ワーニング</td>     </tr>     <tr>       <td>２</td>       <td>エラー</td>     </tr>   </tbody> </table>")
  public Integer getLevel() {
    return level;
  }

  public void setLevel(Integer level) {
    this.level = level;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegulationsResponseRegulationsInfo regulationsResponseRegulationsInfo = (RegulationsResponseRegulationsInfo) o;
    return Objects.equals(this.exchange, regulationsResponseRegulationsInfo.exchange) &&
        Objects.equals(this.product, regulationsResponseRegulationsInfo.product) &&
        Objects.equals(this.side, regulationsResponseRegulationsInfo.side) &&
        Objects.equals(this.reason, regulationsResponseRegulationsInfo.reason) &&
        Objects.equals(this.limitStartDay, regulationsResponseRegulationsInfo.limitStartDay) &&
        Objects.equals(this.limitEndDay, regulationsResponseRegulationsInfo.limitEndDay) &&
        Objects.equals(this.level, regulationsResponseRegulationsInfo.level);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exchange, product, side, reason, limitStartDay, limitEndDay, level);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegulationsResponseRegulationsInfo {\n");
    
    sb.append("    exchange: ").append(toIndentedString(exchange)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    side: ").append(toIndentedString(side)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    limitStartDay: ").append(toIndentedString(limitStartDay)).append("\n");
    sb.append("    limitEndDay: ").append(toIndentedString(limitEndDay)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
