/*
 * kabuステーションAPI
 * # 定義情報   REST APIのコード一覧、エンドポイントは下記リンク参照     - [REST APIコード一覧](../ptal/error.html)
 *
 * OpenAPI spec version: 1.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.RegulationsResponseRegulationsInfo;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * RegulationsResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-04-09T08:07:59.802Z[GMT]")
public class RegulationsResponse {
  @SerializedName("Symbol")
  private String symbol = null;

  @SerializedName("RegulationsInfo")
  private List<RegulationsResponseRegulationsInfo> regulationsInfo = null;

  public RegulationsResponse symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * 銘柄コード&lt;br&gt; ※対象商品は、株式のみ
   * @return symbol
  **/
  @Schema(description = "銘柄コード<br> ※対象商品は、株式のみ")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public RegulationsResponse regulationsInfo(List<RegulationsResponseRegulationsInfo> regulationsInfo) {
    this.regulationsInfo = regulationsInfo;
    return this;
  }

  public RegulationsResponse addRegulationsInfoItem(RegulationsResponseRegulationsInfo regulationsInfoItem) {
    if (this.regulationsInfo == null) {
      this.regulationsInfo = new ArrayList<RegulationsResponseRegulationsInfo>();
    }
    this.regulationsInfo.add(regulationsInfoItem);
    return this;
  }

   /**
   * 規制情報
   * @return regulationsInfo
  **/
  @Schema(description = "規制情報")
  public List<RegulationsResponseRegulationsInfo> getRegulationsInfo() {
    return regulationsInfo;
  }

  public void setRegulationsInfo(List<RegulationsResponseRegulationsInfo> regulationsInfo) {
    this.regulationsInfo = regulationsInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegulationsResponse regulationsResponse = (RegulationsResponse) o;
    return Objects.equals(this.symbol, regulationsResponse.symbol) &&
        Objects.equals(this.regulationsInfo, regulationsResponse.regulationsInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, regulationsInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegulationsResponse {\n");
    
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    regulationsInfo: ").append(toIndentedString(regulationsInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
